# simple_motion_pkg default parameters
path_follower:
  ros__parameters:
    path_topic: "/planned_path"
    cmd_vel_topic: "/a300_00000/cmd_vel"
    base_frame: "base_link"
    global_frame: "map"
    lookahead_distance: 0.5
    max_linear_vel: 0.4
    max_angular_vel: 1.0
    kp_linear: 0.5
    kp_angular: 1.5
    goal_tolerance: 0.25
    control_rate: 10.0
    use_sim_time: true
